#!/usr/bin/env python3
"""
Converts supabase/seed/blog_posts_seed.json into a single, consolidated,
copy-paste-ready SQL file: supabase/seed/blog_posts_insert.sql

This is OPTIONAL — the live website does not depend on Supabase at all (it's
statically generated straight from the content files, see
adarshr12/website's scripts/generate-blog.mjs). Only run/use this if you
want the content mirrored into Supabase too, e.g. for a future CMS/admin
view or in-app search.

Usage:
    python3 supabase/scripts/seed_to_sql.py

Then, in the Supabase Dashboard -> SQL Editor: paste the contents of
supabase/seed/blog_posts_insert.sql and click Run. Requires
migrations/0001_blog_schema.sql and seed/pillars_seed.sql to have been run
first (one-time setup, also just copy-paste-and-run in the SQL Editor).
Safe to re-run any time — every row is an upsert keyed on slug.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SEED_JSON = ROOT / "supabase" / "seed" / "blog_posts_seed.json"
OUT_SQL = ROOT / "supabase" / "seed" / "blog_posts_insert.sql"


def sql_text(value):
    """Dollar-quoted string literal — avoids escaping issues with quotes/apostrophes in article text."""
    if value is None:
        return "NULL"
    return f"$md${value}$md$"


def sql_text_array(items):
    if not items:
        return "'{}'"
    escaped = [str(i).replace("'", "''") for i in items]
    joined = ",".join(f'"{e}"' for e in escaped)
    return f"'{{{joined}}}'"


def sql_jsonb(obj):
    return f"$json${json.dumps(obj, ensure_ascii=False)}$json$::jsonb"


def sql_int_or_null(value):
    return "NULL" if value is None else str(int(value))


def build_insert(post):
    columns = [
        "slug", "title", "meta_description", "primary_keyword", "secondary_keywords",
        "cluster", "priority", "topic_id", "content_md", "quick_facts", "faq",
        "schema_types", "status", "word_count", "last_updated",
    ]
    values = [
        sql_text(post["slug"]),
        sql_text(post["title"]),
        sql_text(post["meta_description"]),
        sql_text(post["primary_keyword"]),
        sql_text_array(post["secondary_keywords"]),
        sql_text(post["cluster"]),
        sql_text(post["priority"]),
        sql_int_or_null(post.get("topic_id")),
        sql_text(post["content_md"]),
        sql_text_array(post["quick_facts"]),
        sql_jsonb(post["faq"]),
        sql_text_array(post["schema_types"]),
        "'draft'",  # review in Supabase before flipping to 'published'
        sql_int_or_null(post.get("word_count")),
        f"'{post['last_updated']}'" if post.get("last_updated") else "CURRENT_DATE",
    ]
    cols_sql = ", ".join(columns)
    vals_sql = ", ".join(values)
    update_sql = ", ".join(f"{c} = excluded.{c}" for c in columns if c != "slug")
    return (
        f"insert into public.blog_posts ({cols_sql})\nvalues ({vals_sql})\n"
        f"on conflict (slug) do update set {update_sql};\n"
    )


def main():
    posts = json.loads(SEED_JSON.read_text(encoding="utf-8"))
    parts = [
        "-- Auto-generated by supabase/scripts/seed_to_sql.py — do not hand-edit.\n"
        f"-- {len(posts)} post(s). Regenerate after every content batch, then re-run this\n"
        "-- whole file in the Supabase SQL Editor (safe to re-run — upserts by slug).\n"
        "-- Requires migrations/0001_blog_schema.sql and seed/pillars_seed.sql first.\n\n"
    ]
    for post in posts:
        parts.append(build_insert(post))
        parts.append("\n")

    OUT_SQL.write_text("".join(parts), encoding="utf-8")
    print(f"Wrote {len(posts)} upsert statement(s) to {OUT_SQL.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
